version: '3.4'
services:
  newsscrpyer:
    image: mscp.linyz.net/news-scrpyer:latest
    restart: always
#     replicas: ${SCRPYER_REPLICAS}
#     deploy:
#       replicas: ${SCRPYER_REPLICAS}
    dns:
      - 8.8.8.8
      - 9.9.9.9
      - 9.0.146.50
    volumes:
      - ./config.json:/app/conf/config.json
# docker-compose pull && docker-compose up -d --force-recreate
# docker-compose up -d --scale newsscrpyer=1
# docker logs newsscrpyer_newsscrpyer_1 -f