version: '3'
services:
  newsscrpyer:
    image: mscp.linyz.net/news-scrpyer:v1a
    deploy:
      replicas: ${SCRPYER_REPLICAS}
    volumes:
      - ./config.json:/app/conf/config.json
# docker-compose pull && docker-compose up -d --force-recreate