version: '2'

services:

  elasticsearch:
    image: mscp.linyz.net/elasticsearch:v6.2.4-ik
    container_name: elasticsearch
    volumes:
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - /home/ylin/elk/elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elk

networks:

  elk:
    driver: bridge

# sysctl -w vm.max_map_count=262144
# ulimit -u 4096
# ulimit -n 65536
# mkdir -p /home/ylin/elk/elasticsearch/data
# chown -R 1000:1000 /home/ylin/elk/elasticsearch/data
