version: '2'
services:
  rabbitMq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
      - "5671:5671"
    environment: 
      RABBITMQ_DEFAULT_PASS: pass
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_VHOST: vhost
      RABBITMQ_VM_MEMORY_HIGH_WATERMARK: 2048MiB
      RABBITMQ_DISK_FREE_LIMIT: 10GB
      HOSTNAME: localhost
    volumes:
      - /home/ylin/rabbitmq/data:/var/lib/rabbitmq