version: '2'

services:
  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.4 
    volumes:
      - ./config/:/usr/share/kibana/config/:ro
    ports:
      - "5601:5601"
    networks:
      - elk
networks:
  elk:
    driver: bridge
